import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');

const ui = read('src/components/ui.tsx');
const header = read('src/components/app-header.tsx');
const home = read('src/app/home.tsx');
const budget = read('src/app/onboarding/budget.tsx');
const newGoal = read('src/app/onboarding/new-goal.tsx');
const adjustGoal = read('src/app/adjust-goal.tsx');
const goal = read('src/app/goal/[id].tsx');
const menu = read('src/components/menu-modal.tsx');
const report = read('src/components/report-modal.tsx');
const reminderDay = read('src/components/reminder-day-modal.tsx');
const balance = read('src/components/balance-modal.tsx');
const rebalance = read('src/components/rebalance-modal.tsx');
const confirmation = read('src/components/confirmation-overlay.tsx');
const loadingOverlay = read('src/components/action-loading-overlay.tsx');
const feedbackBanner = read('src/components/feedback-banner.tsx');
const theme = read('src/constants/theme.ts');
const planSummary = read('src/components/plan-summary.tsx');

assert.match(home, /Un projet\./);
assert.match(home, /Un geste par mois\./);
assert.doesNotMatch(home, /CHECKLIST/);
assert.doesNotMatch(home, /<AppHeader/);

assert.match(ui, /footer\?: ReactNode/);
assert.match(ui, /styles\.screenFooter/);
assert.match(ui, /export function StepIndicator/);
assert.match(ui, /ActivityIndicator/);
assert.match(ui, /loadingLabel\?: string/);
assert.match(ui, /styles\.buttonLoadingContent/);
assert.match(ui, /withTiming/);
assert.match(ui, /ReduceMotion\.System/);
assert.match(ui, /numberOfLines=\{1\}/);
assert.match(ui, /adjustsFontSizeToFit/);
assert.match(ui, /minimumFontScale=\{0\.82\}/);
assert.match(ui, /minHeight: 44/);
assert.match(ui, /paddingVertical: 12/);
assert.match(ui, /label\?: string/);
assert.match(ui, /target <= 14/);
assert.match(ui, /target >= 86/);
assert.match(ui, /styles\.progressMarkerArrow/);
assert.match(theme, /card: 22/);
assert.match(theme, /button: 18/);
assert.match(theme, /screen: 16/);
assert.match(theme, /card: 18/);
assert.match(planSummary, /padding: 18/);

assert.match(header, /delayLongPress=\{700\}/);
assert.match(header, /title\?: string/);
assert.match(header, /width: 40/);

assert.doesNotMatch(budget, /<StepIndicator/);
assert.doesNotMatch(budget, /Étape 1 sur 3/);
assert.match(budget, /marge de sécurité de 20/);

assert.match(ui, /labels = \['Projet', 'Rythme'\]/);
assert.match(ui, /Étape \$\{current\} sur \$\{total\}/);
assert.match(newGoal, /useState<1 \| 2>\(1\)/);
assert.match(newGoal, /subtitle=\{`Étape \$\{step\} sur 2`\}/);
assert.match(newGoal, /<StepIndicator current=\{step\} labels=\{\['Projet', 'Rythme'\]\} \/>/);
assert.doesNotMatch(newGoal, /sur 3/);
assert.match(newGoal, /\['emergency', 'car', 'moving', 'travel', 'other'\]/);
assert.match(newGoal, /CATEGORY_LABELS\[c\]/);
assert.match(newGoal, /category === 'other' \? 'Choisis un nom pour ton projet'/);
assert.doesNotMatch(newGoal, /editId|Ajuster le plan/);
assert.match(newGoal, /Continuer vers le rythme/);
assert.match(newGoal, /loading=\{saving\}/);
assert.match(newGoal, /loadingLabel="Création…"/);
assert.match(newGoal, /<ActionLoadingOverlay/);
assert.match(newGoal, /feedback: 'created'/);
assert.match(newGoal, /rhythmCardSelected: \{ backgroundColor: colors\.cardSoft/);
assert.match(newGoal, /Ton budget mensuel/);
assert.match(newGoal, />Revenus</);
assert.match(newGoal, />Charges fixes</);
assert.match(newGoal, />Dépenses</);
assert.match(newGoal, /Projets en cours \(\{activeExistingGoals\.length\}\)/);
assert.match(newGoal, />Reste réellement disponible</);
assert.match(
  newGoal,
  /budget\.income - budget\.fixedCharges - budget\.variableExpenses - existingEffort/
);
assert.match(newGoal, /prudentCapacity\(budget\) - existingEffort/);
assert.match(newGoal, /Capacité prudente encore disponible :/);
assert.match(newGoal, /remainingAfterExistingGoals < 0/);
assert.match(newGoal, /accessibilityLabel="Ajuster le budget"/);
assert.match(newGoal, /params: \{ returnToGoal: '1' \}/);
assert.match(budget, /returnToGoal === '1'/);
assert.match(budget, /standalone === '1'/);

assert.match(adjustGoal, /Les paramètres utiles, en un seul écran/);
assert.match(adjustGoal, /Le nom et le type de projet restent inchangés/);
assert.match(adjustGoal, /label="Nouveau montant cible"/);
assert.match(adjustGoal, /label="Nouvelle date cible"/);
assert.match(adjustGoal, /label="Jour de rappel \(1 à 28\)"/);
assert.match(adjustGoal, /Rythme des versements/);
assert.match(adjustGoal, /Avant → après/);
assert.match(adjustGoal, /label: 'Versement conseillé'/);
assert.match(adjustGoal, /label: 'Mois le plus élevé'/);
assert.match(adjustGoal, /targetAmount: parsedTarget!/);
assert.match(adjustGoal, /changeReminderDay\(updated, reminderDay\)/);
assert.match(adjustGoal, /loadingLabel="Mise à jour…"/);
assert.match(adjustGoal, /<ActionLoadingOverlay/);
assert.match(adjustGoal, /feedback: 'adjusted'/);
assert.doesNotMatch(adjustGoal, /<StepIndicator|Quel projet veux-tu préparer/);

assert.match(goal, /<Screen footer=\{tabBar\}>/);
assert.match(goal, /schedule\.slice\(0, 2\)/);
assert.match(goal, /label=\{`Versement fait \(\$\{formatEuro\(suggested\)\}\)`\}/);
assert.match(goal, /loading=\{actionLoading\}/);
assert.match(goal, /loadingLabel="Enregistrement…"/);
assert.match(goal, /<ActionLoadingOverlay/);
assert.match(goal, /<FeedbackBanner/);
assert.match(goal, /Rappel reporté/);
assert.match(goal, /Jour de rappel modifié/);
assert.match(goal, /accessibilityRole="tab"/);
assert.match(goal, /tabActive: \{ backgroundColor: colors\.accent/);
assert.match(goal, /<ProgressBar pct=\{pct\} label=\{`\$\{pct\} % atteint`\}/);
assert.match(goal, /styles\.progressFooter/);
assert.match(goal, /Cible \{formatDate\(goal\.targetDate\)\}/);
assert.doesNotMatch(goal, /Solde global (?:pas encore )?confirmé/);
assert.match(goal, /Jour de rappel : le \{goal\.reminderDay\} · Modifier/);
assert.match(goal, /accessibilityLabel="Expliquer le solde réel"/);
assert.match(goal, /À quoi sert le solde réel/);
assert.match(goal, /Rien n’est connecté à ta banque/);

assert.match(menu, /justifyContent: 'flex-end'/);
assert.match(menu, /styles\.grabber/);
assert.doesNotMatch(menu, /label="Accueil"/);
assert.doesNotMatch(menu, /variant="dark"/);
assert.match(menu, /const orderedGoals = activeGoal/);
assert.match(menu, /\[activeGoal, \.\.\.goals\.filter/);
assert.match(menu, /useSafeAreaInsets/);
assert.match(menu, /Math\.max\(insets\.bottom \+ 8, 20\)/);
assert.match(menu, /params: \{ standalone: '1' \}/);
assert.match(menu, /pathname: '\/adjust-goal'/);
assert.match(menu, /params: \{ id: currentGoalId \}/);
assert.match(menu, /contentInsetAdjustmentBehavior="automatic"/);
assert.match(menu, /styles\.actionList/);
assert.match(menu, /minimumFontScale=\{0\.85\}/);
assert.match(menu, /style=\{styles\.actionChevron\}>›/);
assert.doesNotMatch(menu, /styles\.actionRow/);
assert.match(menu, /event\.stopPropagation\(\)/);

assert.match(report, /loading=\{saving\}/);
assert.match(report, /loadingLabel="Programmation…"/);
assert.match(report, /label="Valider la date"/);
assert.match(report, /style=\{\{ flex: 1\.2 \}\}/);
assert.match(confirmation, /ZoomIn/);
assert.match(confirmation, /FadeInUp\.delay/);
assert.match(confirmation, /Objectif atteint/);
assert.match(confirmation, /ReduceMotion\.System/);
assert.match(reminderDay, /loadingLabel="Mise à jour…"/);
assert.match(balance, /loadingLabel="Recalcul…"/);
assert.match(rebalance, /loadingLabel="Application…"/);
assert.match(loadingOverlay, /setTimeout\(\(\) => setShown\(true\), delay\)/);
assert.match(loadingOverlay, /FadeInUp/);
assert.match(loadingOverlay, /ReduceMotion\.System/);
assert.match(feedbackBanner, /FadeInDown/);
assert.match(feedbackBanner, /FadeOutUp/);
assert.match(feedbackBanner, /setTimeout\(onFinished, duration\)/);
assert.match(feedbackBanner, /ReduceMotion\.System/);

console.log('Design mobile validé : accueil, parcours, projet, menu, chargements et animations.');
